### ISSUE TITLE
Add something so we can load image in a BytesIO Object

### ISSUE THREAD

**Issue by SQWiperYT** [vgalin/html2image#2]

**Comment by SQWiperYT** [comment]
Also why saving html and css files are compulsory?

**Comment by vgalin** [comment]
Hi @SQWiperYT, thank you for the issue.
As it is explained in the readme of the project, html2image does not generate images itself and rely on existing web browsers to do so. Thanks to this, when you take screenshots of a page, these will look exactly like what you see yourself when you open them in your browser.

> why saving html and css files are compulsory?

Existing files are copied and strings are materialized, both of them, in a directory because web browsers can only handle remote or local resources : in our use case, the files have to exist somewhere on your machine.

I hope this will help you understand how the package work.

And to answer the issue itself :  I'm not sure if this has a place in the package.
In a way, the only thing that html2image does is finding a browser and asking it kindly to handle some files that were carefully put together in a way that they form a coherent web page. From this on, the browser does all the work.  

As html2image does not generates the images itself, it would have to load the image to access to its content and to potentially create a BytesIO object. But In my opinion (for this moment), doing anything with the generated image files afterward feel too much as an extra step and is not part of the purpose of the package.

In the end, I will think about it, but for the time being, it is your role to handle the generated files and to transform them in whatever format you desire. As a side note, your issue made me wonder if it would be a good idea for the `screenshot` method to return the path of the generated image, so you could directly do something with the file if you want.

**Comment by vgalin** [comment]
The way the package work, from the user perspective, will change in the next version.
The "loading" of the file will be obscured by the new `screenshot` method (that will return the path of the generated images).
As a result, I will close the issue. Thank you for the feedback!
