### ISSUE TITLE
html 2 pillow

### ISSUE THREAD

**Issue by alex93skr** [vgalin/html2image#36]
Question. Can I send a screenshot to Pillow directly in memory without saving it to disk? Thanks

**Comment by vgalin** [comment]
Hello, this package is only but a wrapper around the headless mode of webrowsers, which only can generate images by creating a file on disk. Because of this, directly creating a Pillow object won't be possible, you'll have to:
- screenshot using html2image
    - remember that the `screenshot` method returns an list of the path to the files generated, it may be useful to open the image(s) with pillow
- create a Pillow image object by opening the image
- do your stuff
- potentially delete the original image(s)

I'm closing the issue as this feature can't be implemented as-is, but feel free to ask questions here or in the [discussions](https://github.com/vgalin/html2image/discussions).
